#!/bin/sh
cd Desktop/
cd Scrivania/
mkdir Gecko
cd Gecko
git clone https://github.com/DarkSideOfWii/Gecko-OS-Patcher
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo "======================================================================="
echo "If You Haven't yet installed git commands, please install it"
echo "with the command"
echo " "
echo "$ sudo apt install git"
echo " "
echo "English:"
echo " "
echo "Thanks to used this patcher, now you can use Gecko OS in your Wii"
echo ":)"
echo " "
echo " "
echo "Italiano:"
echo " "
echo "Grazie per aver usato questo patcher, ora potrai usare Gecko OS"
echo "nella tua vecchia Wii"
echo ":)"
echo " "
echo " "
echo "Copyright Boost Software 2022©, Copyright Joshua Faganello 2022©,"
echo "Copyright Homebrew 2022©"
echo "The renaming or the stealing of this domain is extremely illegal"
echo "and can be punished with a legal process."
echo "======================================================================="
